from django.conf.urls import url

from .views import (
    AppointmentsOnADayView,
    ClientListView,
    ClientPricingView,
    ClientView,
    DatesWithAppointmentsView,
    InvitationView,
    NearbyClientsView,
    ServiceTemplateSetDetailsView,
    ServiceTemplateSetListView,
    StylistAppointmentListCreateView,
    StylistAppointmentPreviewView,
    StylistAppointmentRetrieveUpdateCancelView,
    StylistAvailabilityView,
    StylistDiscountsView,
    StylistHomeView,
    StylistMaximumDiscountView,
    StylistServiceListView,
    StylistServicePricingView,
    StylistServiceView,
    StylistSettingsRetrieveView,
    StylistSettingsView,
    StylistSpecialAvailabilityDateView,
    StylistTodayView,
    StylistView,
)

app_name = 'stylist'

urlpatterns = [
    url('^profile$', StylistView.as_view(), name='profile'),
    url('^settings$', StylistSettingsRetrieveView.as_view(), name='settings'),
    url('^service-template-sets$', ServiceTemplateSetListView.as_view()),
    url('^service-template-sets/(?P<template_set_uuid>[0-9a-f\-]+)$',
        ServiceTemplateSetDetailsView.as_view()),
    url('^services$', StylistServiceListView.as_view()),
    url('^services/(?P<uuid>[0-9a-f\-]+)$', StylistServiceView.as_view(), name='service'),
    url('^services/pricing$', StylistServicePricingView.as_view(), name='service-pricing'),
    url('^availability/weekdays$',
        StylistAvailabilityView.as_view(), name='availability_weekdays'),
    url('^discounts$', StylistDiscountsView.as_view(), name='discounts'),
    url('^maximum-discount$',
        StylistMaximumDiscountView.as_view(), name='maximum-discounts'),
    url('^today$', StylistTodayView.as_view(), name='today'),
    url('^home$', StylistHomeView.as_view(), name='home'),
    url('^appointments$', StylistAppointmentListCreateView.as_view(), name='appointments'),
    url('^appointments/oneday$', AppointmentsOnADayView.as_view(), name='one-day-appointments'),
    url('^appointments/dates-with-appointments$',
        DatesWithAppointmentsView.as_view(), name='dates-with-appointments'),
    url('^appointments/preview$', StylistAppointmentPreviewView.as_view(),
        name='appointment-preview'),
    url('^appointments/(?P<appointment_uuid>[0-9a-f\-]+)$',
        StylistAppointmentRetrieveUpdateCancelView.as_view(), name='appointment'),
    url('^invitations$', InvitationView.as_view(), name='invitation'),
    url('^clients$', ClientListView.as_view(), name='my-clients'),
    url('^clients/(?P<client_uuid>[0-9a-f\-]+)$', ClientView.as_view(), name='client'),
    url('^clients/pricing$', ClientPricingView.as_view(), name='client-pricing'),
    url('^nearby-clients$', NearbyClientsView.as_view(), name='nearby-client'),
    url('^common-settings$', StylistSettingsView.as_view(), name='common-settings'),
    url('^availability/special/(?P<date>\d{4}-\d{1,2}-\d{1,2})$',
        StylistSpecialAvailabilityDateView.as_view(), name='special-availability'),
]
