version: '3.2'

services:
  web:
    build: .
    volumes:
      - made-backend:/madebeauty
    command: make run-inside-docker
    ports:
      - "8000:8000"
volumes:
  made-backend:
    driver: local