# Generated by Django 2.1 on 2018-11-07 18:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181107_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=notifications.models.default_json_field_value, null=True),
        ),
    ]
