# Generated by Django 2.1 on 2018-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20181107_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='device_acked_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pending_to_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
