# Generated by Django 2.1 on 2018-11-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20181108_1601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
    ]
