# Generated by Django 2.1 on 2018-12-03 09:15

from django.db import migrations, models
import notifications.types


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20181115_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_via_channel',
            field=models.CharField(choices=[('sms', 'SMS message'), ('push', 'Push Notification')], default=notifications.types.NotificationChannel('push'), max_length=16, null=True),
        ),
    ]
