# Generated by Django 2.1 on 2018-12-03 09:15

from django.db import migrations

from notifications.types import NotificationChannel


def mark_previous_sms_messages_non_pending_to_send(apps, schema_editor):
    """Mark all previously entered SMS message as non-pending-to-send"""
    Notification = apps.get_model('notifications', 'Notification')  # noqa
    Notification.objects.filter(
        channel=NotificationChannel.SMS, pending_to_send=True
    ).update(pending_to_send=False)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_sent_via_channel'),
    ]

    operations = [
        migrations.RunPython(
            mark_previous_sms_messages_non_pending_to_send, migrations.RunPython.noop
        )
    ]
