# Generated by Django 2.1 on 2018-12-03 09:15

from django.db import migrations
from django.db.models import F


def populate_sent_via_channel(apps, schema_editor):
    """Mark all previously entered SMS message as non-pending-to-send"""
    Notification = apps.get_model('notifications', 'Notification')  # noqa
    Notification.objects.filter(
        sent_at=None
    ).update(sent_via_channel=F('channel'))


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20181203_0415'),
    ]

    operations = [
        migrations.RunPython(
            populate_sent_via_channel, migrations.RunPython.noop
        )
    ]
