# Generated by Django 2.1 on 2018-12-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20181203_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_via_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS message'), ('push', 'Push Notification')], default=None, max_length=16, null=True),
        ),
    ]
