# Generated by Django 2.1 on 2018-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20181219_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='twilio_message_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
