# Generated by Django 2.1 on 2019-03-05 15:59

from django.db import migrations, models
import notifications.types


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_notification_email_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS message'), ('push', 'Push Notification'), ('email', 'Email Notification')], default=notifications.types.NotificationChannel('push'), max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='forced_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS message'), ('push', 'Push Notification'), ('email', 'Email Notification')], default=None, max_length=16, null=True, verbose_name='Specifically selected channel for current notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_via_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS message'), ('push', 'Push Notification'), ('email', 'Email Notification')], default=None, max_length=16, null=True),
        ),
    ]
