# Generated by Django 2.0.3 on 2018-05-11 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0022_auto_20180510_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_uuid', models.UUIDField(null=True)),
                ('service_name', models.CharField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_start_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='client.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_appointments', to=settings.AUTH_USER_MODEL)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon.Stylist')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
