# Generated by Django 2.0.3 on 2018-05-11 18:45

import appointment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', appointment.models.AppointmentAllObjectsManager()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
