# Generated by Django 2.0.3 on 2018-05-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20180511_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
