# Generated by Django 2.0.3 on 2018-05-30 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20180516_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_uuid', models.UUIDField()),
                ('service_name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_original', models.BooleanField(verbose_name='Service with which appointment was created')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointment.Appointment')),
            ],
            options={
                'db_table': 'appointment_service',
            },
        ),
    ]
