# Generated by Django 2.0.3 on 2018-05-30 11:50
from uuid import uuid4

from django.db import migrations


def migrate_services(apps, schema_editor):
    AppointmentService = apps.get_model('appointment', 'AppointmentService')
    Appointment = apps.get_model('appointment', 'Appointment')
    for appointment in Appointment.all_objects.filter(services__isnull=True):
        AppointmentService.objects.create(
            appointment=appointment,
            uuid=uuid4(),
            service_uuid=appointment.service_uuid,
            service_name=appointment.service_name,
            client_price=appointment.client_price,
            regular_price=appointment.regular_price,
            duration=appointment.duration,
            is_original=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointmentservice'),
    ]

    operations = [
        migrations.RunPython(migrate_services, migrations.RunPython.noop),
    ]
