# Generated by Django 2.0.3 on 2018-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_auto_20180625_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='applied_discount',
            field=models.CharField(choices=[('first_booking', 'First Booking'), ('revisit_within_1_week', 'Revisit within 1 week'), ('revisit_within_2_weeks', 'Revisit within 2 weeks'), ('weekday', 'Weekday')], max_length=30, null=True),
        ),
    ]
