# Generated by Django 2.0.3 on 2018-07-02 12:30

from django.db import migrations

def convert_to_verbose_choice(apps, schema_editor):
    AppointmentService = apps.get_model('appointment', 'appointmentservice')
    AppointmentService.objects.filter(
        applied_discount='1').update(applied_discount='first_booking')
    AppointmentService.objects.filter(
        applied_discount='2').update(applied_discount='revisit_within_1_week')
    AppointmentService.objects.filter(
        applied_discount='3').update(applied_discount='revisit_within_2_weeks')
    AppointmentService.objects.filter(
        applied_discount='4').update(applied_discount='weekday')

def convert_to_numeric_choice(apps, schema_editor):
    AppointmentService = apps.get_model('appointment', 'appointmentservice')
    AppointmentService.objects.filter(
        applied_discount='first_booking').update(applied_discount='1')
    AppointmentService.objects.filter(
        applied_discount='revisit_within_1_week').update(applied_discount='2')
    AppointmentService.objects.filter(
        applied_discount='revisit_within_2_weeks').update(applied_discount='3')
    AppointmentService.objects.filter(
        applied_discount='weekday').update(applied_discount='4')


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_auto_20180702_0828'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_verbose_choice,
            convert_to_numeric_choice
        ),
    ]
