# Generated by Django 2.0.3 on 2018-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_auto_20180702_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='applied_discount',
            field=models.CharField(choices=[('first_booking', 'First Booking'), ('revisit_within_1_week', 'Revisit within 1 week'), ('revisit_within_2_weeks', 'Revisit within 2 weeks'), ('revisit_within_3_weeks', 'Revisit within 3 weeks'), ('revisit_within_4_weeks', 'Revisit within 4 weeks'), ('revisit_within_5_weeks', 'Revisit within 5 weeks'), ('revisit_within_6_weeks', 'Revisit within 6 weeks'), ('weekday', 'Weekday')], max_length=30, null=True),
        ),
    ]
