# Generated by Django 2.0.3 on 2018-07-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20180720_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
