# Generated by Django 2.0.3 on 2018-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_appointment_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
