# Generated by Django 2.1 on 2018-08-24 20:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_auto_20180810_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.874999999999999555910790150'), max_digits=4),
        ),
    ]
