# Generated by Django 2.1 on 2018-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_appointment_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=8.875, max_digits=5),
        ),
    ]
