# Generated by Django 2.1 on 2018-08-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_auto_20180829_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='card_fee_percentage',
            field=models.DecimalField(decimal_places=3, default=2.75, max_digits=5),
        ),
    ]
