# Generated by Django 2.1 on 2018-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0025_appointment_card_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=6.5, max_digits=5),
        ),
    ]
