# Generated by Django 2.1 on 2018-10-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_client_location_from_zipcode'),
        ('appointment', '0027_appointment_phone_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='real_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='client.Client'),
        ),
    ]
