# Generated by Django 2.1 on 2018-10-10 11:37

from django.db import migrations


def populate_real_client_field(apps, schema_editor):
    Appointment = apps.get_model('appointment', 'Appointment')
    Client = apps.get_model('client', 'Client')
    for appointment in Appointment.all_objects.filter(
            client__isnull=False, real_client__isnull=True).iterator():
        real_client: Client = appointment.client.client
        appointment.real_client = real_client
        appointment.save(update_fields=['real_client', ])


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0028_appointment_real_client'),
    ]

    operations = [
        migrations.RunPython(populate_real_client_field, migrations.RunPython.noop)
    ]
