# Generated by Django 2.1 on 2018-10-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0029_auto_20181010_0737'),
        ('core', '0031_auto_20181011_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
    ]
