# Generated by Django 2.1 on 2018-10-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_client_location_from_zipcode'),
        ('appointment', '0030_remove_appointment_client'),
        ('core', '0031_auto_20181011_1126')
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='real_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_old', to='client.Client'),
        ),
    ]
