# Generated by Django 2.1 on 2018-10-11 16:47

from django.db import migrations


def populate_client_field(apps, schema_editor):
    Appointment = apps.get_model('appointment', 'Appointment')
    Client = apps.get_model('client', 'Client')
    for appointment in Appointment.all_objects.filter(
            client__isnull=True, real_client__isnull=False).iterator():
        client: Client = appointment.real_client
        appointment.client = client
        appointment.save(update_fields=['client', ])


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0031_auto_20181011_1158'),
    ]

    operations = [
        migrations.RunPython(populate_client_field, migrations.RunPython.noop)
    ]
