# Generated by Django 2.1 on 2018-10-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0032_auto_20181011_1247'),
        ('core', '0032_auto_20181011_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='real_client',
        ),
    ]
