# Generated by Django 2.1 on 2018-11-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0033_remove_appointment_real_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=4.5, max_digits=5),
        ),
    ]
