# Generated by Django 2.1 on 2018-12-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0037_auto_20181204_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='card_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=2.75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', related_query_name='appointment', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_google_calendar_added_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist_google_calendar_added_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=4.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_card_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_client_price_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
