# Generated by Django 2.1 on 2018-12-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0038_auto_20181206_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', related_query_name='service', to='appointment.Appointment'),
        ),
    ]
