# Generated by Django 2.1 on 2019-01-16 14:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0039_auto_20181211_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount_type',
            field=models.CharField(choices=[('first_booking', 'First Booking'), ('revisit_within_1_week', 'Revisit within 1 week'), ('revisit_within_2_weeks', 'Revisit within 2 weeks'), ('revisit_within_3_weeks', 'Revisit within 3 weeks'), ('revisit_within_4_weeks', 'Revisit within 4 weeks'), ('revisit_within_5_weeks', 'Revisit within 5 weeks'), ('revisit_within_6_weeks', 'Revisit within 6 weeks'), ('weekday', 'Weekday')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_discount_percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
