# Generated by Django 2.1 on 2019-01-16 14:36

from django.db import migrations


def populate_discount_on_appointments(apps, schema_editor):
    Appointment = apps.get_model('appointment', 'Appointment')
    appointments_to_populate = Appointment.objects.filter(
        service__isnull=False,
        status='new',
        total_discount_percentage=0
    )
    for appointment in appointments_to_populate.iterator():
        if appointment.services.filter(applied_discount__isnull=False).exists():
            service = appointment.services.filter(applied_discount__isnull=False).last()
            appointment.discount_type = service.applied_discount
            appointment.total_discount_percentage = service.discount_percentage
            appointment.save(update_fields=['discount_type', 'total_discount_percentage'])


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0040_auto_20190116_0935'),
    ]

    operations = [
        migrations.RunPython(populate_discount_on_appointments, migrations.RunPython.noop)
    ]
