# Generated by Django 2.0.3 on 2018-04-18 14:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_stylistservice_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York'),
        ),
    ]
