# Generated by Django 2.0.3 on 2018-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20180418_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='photo',
        ),
    ]
