# Generated by Django 2.0.3 on 2018-04-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_remove_salon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='profile_photo',
        ),
    ]
