# Generated by Django 2.0.3 on 2018-04-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20180420_1501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salon',
            table='salon',
        ),
        migrations.AlterModelTable(
            name='servicetemplate',
            table='service_template',
        ),
        migrations.AlterModelTable(
            name='servicetemplateset',
            table='service_template_set',
        ),
        migrations.AlterModelTable(
            name='stylist',
            table='stylist',
        ),
        migrations.AlterModelTable(
            name='stylistavailableday',
            table='stylist_available_day',
        ),
        migrations.AlterModelTable(
            name='stylistdaterangediscount',
            table='stylist_date_range_discount',
        ),
        migrations.AlterModelTable(
            name='stylistearlyrebookdiscount',
            table='stylist_early_rebook_discount',
        ),
        migrations.AlterModelTable(
            name='stylistfirsttimebookdiscount',
            table='stylist_first_time_book_discount',
        ),
        migrations.AlterModelTable(
            name='stylistservice',
            table='stylist_service',
        ),
        migrations.AlterModelTable(
            name='stylistservicephotosample',
            table='stylist_service_photo_sample',
        ),
        migrations.AlterModelTable(
            name='stylistweekdaydiscount',
            table='stylist_weekday_discount',
        ),
    ]
