# Generated by Django 2.0.3 on 2018-04-25 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid

import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_auto_20180423_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
            options={
                'db_table': 'service_category',
            },
        ),
        migrations.RemoveField(
            model_name='servicetemplateset',
            name='templates',
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='templateset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='salon.ServiceTemplateSet'),
        ),
        migrations.AddField(
            model_name='servicetemplateset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplateset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='salon.ServiceCategory'),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.ServiceCategory'),
        ),
        migrations.AlterModelManagers(
            name='stylistservice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', salon.models.StylistServiceWithDeletedManager()),
            ],
        ),
    ]
