# Generated by Django 2.0.3 on 2018-04-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0017_auto_20180427_0634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StylistAvailableDay',
            new_name='StylistAvailableWeekDay',
        ),
    ]
