# Generated by Django 2.0.3 on 2018-04-30 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0018_auto_20180427_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='service_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
