# Generated by Django 2.0.3 on 2018-05-10 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_auto_20180430_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylistearlyrebookdiscount',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='stylistfirsttimebookdiscount',
            name='stylist',
        ),
        migrations.AddField(
            model_name='stylist',
            name='first_time_book_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_1_week_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_2_weeks_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='StylistEarlyRebookDiscount',
        ),
        migrations.DeleteModel(
            name='StylistFirstTimeBookDiscount',
        ),
    ]
