# Generated by Django 2.0.3 on 2018-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0024_auto_20180529_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='is_discount_configured',
            field=models.BooleanField(default=False),
        ),
    ]
