# Generated by Django 2.0.3 on 2018-06-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0026_auto_20180604_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='service_time_gap',
            field=models.DurationField(default=datetime.timedelta(0, 900)),
        ),
    ]
