# Generated by Django 2.0.3 on 2018-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0031_remove_stylistservice_service_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='has_invited_clients',
            field=models.BooleanField(default=False),
        ),
    ]
