# Generated by Django 2.0.3 on 2018-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('stylist', 'Stylist'), ('staff', 'Staff')], max_length=10, null=True),
        ),
    ]
