# Generated by Django 2.0.3 on 2018-04-21 11:39

from django.db import migrations
from core.choices import USER_ROLE


def assign_user_role(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        if user.is_superuser or user.is_staff:
            user.role = USER_ROLE.staff
        else:
            user.role = USER_ROLE.stylist
        user.save(update_fields=['role', ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_role'),
    ]

    operations = [
        migrations.RunPython(assign_user_role, migrations.RunPython.noop),
    ]
