# Generated by Django 2.0.3 on 2018-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_temporaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist'), ('staff', 'Staff')], max_length=10),
        ),
    ]
