# Generated by Django 2.0.3 on 2018-06-11 12:17

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180515_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('31b54e4a-7a91-432b-b317-1bb2445e7ee0'), null=True),
        ),
        migrations.AlterField(
            model_name='temporaryfile',
            name='file',
            field=models.FileField(upload_to=core.models.generate_upload_file_name),
        ),
        migrations.AlterField(
            model_name='temporaryfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
