# Generated by Django 2.0.3 on 2018-06-11 12:17
import uuid

from django.db import migrations


def populate_user_uuids(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid', ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180611_0817'),
    ]

    operations = [
        migrations.RunPython(populate_user_uuids, migrations.RunPython.noop),
    ]
