# Generated by Django 2.0.3 on 2018-06-21 13:42
import random

from django.db import migrations, models
from django.db.models import Count

def alter_repeated_phone_numbers(apps, schema_editor):
    User = apps.get_model("core", "User")
    random_numbers = range(1, 999)
    while True:
        repeated_phone_numbers = User.objects.values('phone').annotate(
            Count('id')).filter(id__count__gt=1).values_list('phone', flat=True)
        if len(repeated_phone_numbers) == 0:
            break
        for user in User.objects.filter(phone__in=repeated_phone_numbers):
            user.phone = "{0}{1}".format(user.phone,str(random.choice(random_numbers)))
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180611_0825'),
    ]

    operations = [
        migrations.RunPython(alter_repeated_phone_numbers, migrations.RunPython.noop),
    ]
