# Generated by Django 2.0.3 on 2018-06-22 18:36

from django.db import migrations

from core.types import UserRole


def remove_client_users(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role=UserRole.CLIENT.value).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180622_0604'),
        ('client','0004_auto_20180622_1231')
    ]

    operations = [
        migrations.RunPython(remove_client_users, migrations.RunPython.noop),
    ]
