# Generated by Django 2.0.3 on 2018-07-05 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180703_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist'), ('staff', 'Staff')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True,
                                   choices=[('client', 'Client'), ('stylist', 'Stylist'), ('staff', 'Staff')],
                                   max_length=10, null=True),
        ),
    ]
