# Generated by Django 2.0.3 on 2018-07-05 15:07

from django.db import migrations


def copy_role_to_temp(apps, schema_editor):
    User = apps.get_model("core", "User")
    users = User.objects.all()
    for user in users:
        user.temp_role = [user.role]
        user.role = None
        user.save(update_fields=['temp_role', 'role'])

def copy_role_from_temp(apps, schema_editor):
    User = apps.get_model("core", "User")
    users = User.objects.all()
    for user in users:
        user.role = user.temp_role[0]
        user.temp_role = []
        user.save(update_fields=['temp_role', 'role'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_temp_role'),
    ]

    operations = [
        migrations.RunPython(copy_role_to_temp, copy_role_from_temp),
    ]
