# Generated by Django 2.0.3 on 2018-07-05 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180705_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist'), ('staff', 'Staff')], max_length=10), blank=True, null=True, size=None),
        ),
    ]
