# Generated by Django 2.0.3 on 2018-07-05 15:30

from django.db import migrations


def copy_role_from_temp(apps, schema_editor):
    User = apps.get_model("core", "User")
    users = User.objects.all()
    for user in users:
        user.role = user.temp_role
        user.save(update_fields=['role'])

def copy_role_to_temp(apps, schema_editor):
    User = apps.get_model("core", "User")
    users = User.objects.all()
    for user in users:
        user.temp_role = user.role
        user.save(update_fields=['temp_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180705_1121'),
    ]

    operations = [
        migrations.RunPython(copy_role_from_temp, copy_role_to_temp),
    ]