# Generated by Django 2.1 on 2018-08-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180705_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSMSCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('role', models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist'), ('staff', 'Staff')], default='client', max_length=10)),
                ('generated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_sms_codes',
            },
        ),
    ]
