# Generated by Django 2.1 on 2018-09-04 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_phonesmscodes'),
    ]

    operations = [
        migrations.RunSQL(
            # Create User if user doesnot exist
            "DO $$"
            "BEGIN"
            "  CREATE USER readonly_user WITH ENCRYPTED PASSWORD 'tgoHSHQKj4CS';"
            "  EXCEPTION WHEN OTHERS THEN"
            "  RAISE NOTICE 'not creating role my_role -- it already exists';"
            "END"
            "$$;"
            # First, grant connect access
            "GRANT CONNECT ON DATABASE {0} TO readonly_user;"
            # Then grant SELECT for all existing tables
            "GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;"
            # Grant select for tables that are newly created
            "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;"
            # Create schema exists by default. Remove them.
            "REVOKE CREATE ON SCHEMA public FROM readonly_user;".format(
                settings.DATABASES['default']['NAME']),

            reverse_sql= "DROP OWNED BY readonly_user;"
            "DROP USER readonly_user;"
        )
    ]