# Generated by Django 2.1 on 2018-09-13 15:06
import logging

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)


def forwards(apps, schema_editor):
    if not settings.READ_ONLY_USER_PASSWORD:
        logger.info("Skipping changing password --environment variable doesnot exist")
        return
    schema_editor.execute(
        "DO $$"
            "BEGIN"
            "  ALTER USER readonly_user WITH PASSWORD '{0}';"
            "  EXCEPTION WHEN OTHERS THEN"
            "  RAISE NOTICE 'not changing password readonly_user -- doesnot exists';"
            "END"
            "$$;".format(
                settings.READ_ONLY_USER_PASSWORD)
    )


def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_create_readonly_user'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards)
    ]
