# Generated by Django 2.1 on 2018-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180925_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesmscodes',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='phonesmscodes',
            unique_together={('phone', 'role')},
        ),
    ]
