# Generated by Django 2.1 on 2018-10-01 20:26

from django.db import migrations


def forwards(apps, schema_editor):
    schema_editor.execute(
        '''
        DO
        $do$
        begin
            create or replace view public.rpt_user as
            select u.id,
                u.is_active,
                u.is_staff,
                u.date_joined,
                u.last_login,
                ('stylist' = ANY( u.role))::int is_stylist,
                ('client' = ANY( u.role))::int is_client,
                (ii.created_client_id is not null)::int is_invitation
            from public.user u
                left join (
                    select c.user_id, max( i.created_client_id) created_client_id
                    from public.client c
                        left join public.client_of_stylist cs
                            on c.id = cs.client_id
                        left join public.invitation i
                            on cs.id = i.created_client_id
                    group by c.user_id) ii
                on u.id = ii.user_id
            where 'staff' != ALL( u.role)
            ;
            

        end
        $do$;
        '''
    )


def backwards(apps, schema_editor):
    schema_editor.execute(
        '''
        DO
        $do$
        begin
            drop view if exists public.rpt_appointment_service;
            drop view if exists public.rpt_distribution_clients_per_stylists;
            drop view if exists public.rpt_distribution_stylists_per_clients;
            drop view if exists public.rpt_distribution_pareto_stylist_client;
            drop view if exists public.rpt_stylist;
            drop view if exists public.rpt_dates;
            drop view if exists public.rpt_user;
            drop view if exists public.rpt_booking;
            drop view if exists public.rpt_staff_client;
            drop view if exists public.rpt_staff_stylist;
            drop view if exists public.rpt_staff_users;
        end
        $do$;
        '''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180927_1112'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
