# Generated by Django 2.1 on 2018-10-11 15:26

from django.db import migrations


def drop_analytic_views(apps, schema_editor):
    schema_editor.execute(
        '''
        DO
        $do$
        begin

            drop view if exists public.rpt_appointment_service cascade;

            drop view if exists public.rpt_distribution_clients_per_stylists cascade;

            drop view if exists public.rpt_distribution_stylists_per_clients cascade;

            drop view if exists public.rpt_distribution_pareto_stylist_client cascade;

            drop view if exists public.rpt_stylist cascade;

            drop view if exists public.rpt_dates cascade;

            drop view if exists public.rpt_booking_h cascade;

            drop view if exists public.rpt_booking cascade;

            drop view if exists public.rpt_staff_client cascade;

            drop view if exists public.rpt_staff_stylist cascade;

            drop view if exists public.rpt_staff_users cascade;

            drop view if exists public.rpt_users_h cascade;

            drop view if exists public.rpt_user cascade;

        end
        $do$;
        '''
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181001_1626'),
        ('appointment', '0029_auto_20181010_0737'),
        ('salon', '0055_auto_20181010_0755'),
    ]

    operations = [
        migrations.RunPython(drop_analytic_views, migrations.RunPython.noop),
    ]
