# Generated by Django 2.1 on 2018-11-15 17:31

from django.db import migrations

def forward(app, schema_editor):
    schema_editor.execute(
        """
        DO $$
        BEGIN
          IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname = 'readonly_user') THEN
            GRANT SELECT ON ALL TABLES IN SCHEMA  public TO readonly_user;
            GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly_user;
            ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO readonly_user;
            ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO readonly_user;
          END IF;
        END $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20181105_1506'),
        ('appointment', '0033_remove_appointment_real_client'),
        ('client', '0022_auto_20181024_1246'),
        ('notifications', '0007_auto_20181115_1213'),
        ('salon', '0069_set_initial_specialities')
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
