# Generated by Django 2.1 on 2018-12-14 15:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20181129_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField()),
                ('user_role', models.CharField(choices=[('client', 'Client'), ('stylist', 'Stylist')], max_length=16)),
                ('app_version', models.CharField(max_length=16)),
                ('app_build', models.IntegerField()),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('app_os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16, null=True)),
            ],
            options={
                'db_table': 'analytics_session',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField()),
                ('auth_session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('view_title', models.CharField(max_length=64)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('analytics_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnalyticsSession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_view',
            },
        ),
    ]
