# Generated by Django 2.1 on 2018-12-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_analyticssession_analyticsview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_stopped_sms',
            field=models.BooleanField(default=False),
        ),
    ]
