# Generated by Django 2.0.3 on 2018-06-22 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
        ('client', '0002_client_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOfStylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_of_stylist', to='salon.Stylist')),
            ],
            options={
                'db_table': 'client_of_stylist',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientofstylist',
            unique_together={('stylist', 'first_name', 'last_name'), ('stylist', 'phone')},
        ),
    ]
