# Generated by Django 2.0.3 on 2018-06-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180622_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientofstylist',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_of_stylist', to='salon.Stylist'),
        ),
    ]
