# Generated by Django 2.0.3 on 2018-07-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import utils.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0038_auto_20180702_1359'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_auto_20180703_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='PhoneSMSCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('generated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_sms_codes',
            },
        ),
        migrations.CreateModel(
            name='PreferredStylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.Stylist')),
            ],
            options={
                'db_table': 'preferred_stylist',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', utils.models.IncludeDeletedManager()),
            ],
        ),
        migrations.CreateModel(
            name='StylistSearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip_addr', models.GenericIPAddressField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stylist_search_request',
            },
        ),
        migrations.AddField(
            model_name='clientofstylist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Client'),
        ),
    ]
