# Generated by Django 2.0.3 on 2018-07-31 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20180720_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistsearchrequest',
            name='user_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='stylistsearchrequest',
            name='user_ip_addr',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
