# Generated by Django 2.1 on 2018-08-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20180803_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneSMSCodes',
        ),
    ]
