# Generated by Django 2.1 on 2018-08-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0051_salon_is_address_geocoded'),
        ('client', '0013_auto_20180822_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientofstylist',
            unique_together={('stylist', 'phone'), ('stylist', 'client')},
        ),
    ]
