# Generated by Django 2.1 on 2018-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20180827_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientofstylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
    ]
