# Generated by Django 2.1 on 2018-10-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_client_location_from_zipcode'),
        ('core', '0032_auto_20181011_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientofstylist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientofstylist',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientofstylist',
            name='stylist',
        ),
        migrations.DeleteModel(
            name='ClientOfStylist',
        ),
    ]
