# Generated by Django 2.1 on 2018-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_client_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
