# Generated by Django 2.1 on 2018-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20181024_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_access_token',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='google_integration_added_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='google_refresh_token',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
