# Generated by Django 2.1 on 2018-11-26 09:00

from django.db import connection, migrations
from django.db.models import F

def populate_client_created_at(apps, schema_editor):
    """
    Populate client's created_at based on user.date_joined in assumption
    that they're equal. It's not totally true for the clients who're also
    stylists, but this is a neglectable edge case
    :return:
    """
    # Django does not support updates on joined fields, so the raw query below
    # must be an equivalent to
    # Client = apps.get_model('client', 'Client')
    # Client.objects.all().update(
    #     created_at=F('user__date_joined')
    # )
    schema_editor.execute(
        """
          update public.client as c set created_at = u.date_joined from public.user as u
          where c.user_id = u.id;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_client_created_at'),
    ]

    operations = [
        migrations.RunPython(populate_client_created_at, migrations.RunPython.noop)
    ]
