# Generated by Django 2.1 on 2018-12-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_auto_20181129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_seen_educational_screens',
            field=models.BooleanField(default=False),
        ),
    ]
