# Generated by Django 2.1 on 2018-11-07 12:27
from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor
from django.db import migrations
from django.db.migrations.state import StateApps


def set_initial_profile_completeness(apps: StateApps, schema_editor: PostGISSchemaEditor):
    Client = apps.get_model('client', 'Client')
    clients = Client.objects.select_related('user').all()
    for client in clients:
        fields = [client.user.first_name,
                  client.user.last_name,
                  client.user.photo,
                  client.email,
                  client.zip_code,
                  client.birthday]
        complete_fields = 0
        total_fields = len(fields)
        for field in fields:
            if field:
                complete_fields += 1
        client.profile_completeness = float(complete_fields / total_fields)
        client.save(update_fields=['profile_completeness'])

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_client_profile_completeness'),
    ]

    operations = [
        migrations.RunPython(code=set_initial_profile_completeness, reverse_code=migrations.RunPython.noop)
    ]
