# Generated by Django 2.1 on 2018-12-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_set_initial_profile_completeness_for_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
