# Generated by Django 2.1 on 2019-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_client_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
