# Generated by Django 2.1 on 2019-02-07 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_client_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistsearchrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stylistsearchrequest',
            name='stylists_found',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
