# Generated by Django 2.1 on 2019-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_auto_20190207_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
