# Generated by Django 2.0.3 on 2018-05-15 11:29

import appointment.types
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0003_auto_20180514_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cancelled_by_client', 'Cancelled by client'), ('cancelled_by_stylist', 'Cancelled by stylist'), ('no_show', 'No show'), ('checked_out', 'Client checked out')], default=appointment.types.AppointmentStatus('new'), max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
