# Generated by Django 2.0.3 on 2018-05-16 18:22

import appointment.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20180515_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cancelled_by_client', 'Cancelled by client'), ('cancelled_by_stylist', 'Cancelled by stylist'), ('no_show', 'No show'), ('checked_out', 'Client checked out')], default=appointment.types.AppointmentStatus('new'), max_length=30),
        ),
    ]
