# Generated by Django 2.0.3 on 2018-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20180530_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='duration',
            field=models.DurationField(),
        ),
    ]
