# Generated by Django 2.0.3 on 2018-05-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20180531_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client_price',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='regular_price',
        ),
    ]
