# Generated by Django 2.0.3 on 2018-06-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20180531_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_uuid',
        ),
    ]
