# Generated by Django 2.0.3 on 2018-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_auto_20180611_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='applied_discount',
            field=models.PositiveIntegerField(choices=[(1, 'First Booking'), (2, 'Revisit within 1 week'), (3, 'Revisit within 2 weeks'), (4, 'Weekday')], null=True),
        ),
    ]
