# Generated by Django 2.0.3 on 2018-06-19 11:43

from django.db import migrations, models
from django.db.models import F

def set_caculated_price(apps, schema_editor):
    AppointmentService = apps.get_model('appointment', 'appointmentservice')
    AppointmentService.objects.filter(
        calculated_price=0).update(calculated_price=F('client_price'))

class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20180618_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='is_price_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_caculated_price,
            migrations.RunPython.noop
        ),
    ]
