# Generated by Django 2.0.3 on 2018-04-09 12:38

from django.conf import settings
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('work_start_at', models.TimeField()),
                ('work_end_at', models.TimeField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salon.Salon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StylistAvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='salon.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StylistDateRangeDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_range_discounts', to='salon.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StylistEarlyRebookDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('minrebook_interval', models.DurationField()),
                ('stylist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='early_rebook_discount', to='salon.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StylistFirstTimeBookDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('stylist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_time_book_discount', to='salon.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.Stylist')),
            ],
        ),
        migrations.CreateModel(
            name='StylistServicePhotoSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('stylist_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_samples', to='salon.StylistService')),
            ],
        ),
        migrations.CreateModel(
            name='StylistWeekdayDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_discounts', to='salon.Stylist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stylistweekdaydiscount',
            unique_together={('stylist', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='stylistavailableday',
            unique_together={('stylist', 'weekday')},
        ),
    ]
