# Generated by Django 2.0.3 on 2018-04-13 16:32

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20180410_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='work_end_at',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='work_start_at',
        ),
        migrations.AlterField(
            model_name='salon',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
    ]
