# Generated by Django 2.0.3 on 2018-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_servicetemplateset'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistservice',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
