# Generated by Django 2.0.3 on 2018-04-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_remove_stylist_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.Salon'),
        ),
    ]
