# Generated by Django 2.0.3 on 2018-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_auto_20180423_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylistservice',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
