# Generated by Django 2.0.3 on 2018-04-30 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_auto_20180430_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stylistservice',
            name='service_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
