# Generated by Django 2.0.3 on 2018-05-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='salon.Stylist'),
        ),
    ]
