# Generated by Django 2.0.3 on 2018-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0025_stylist_is_discount_configured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
