# Generated by Django 2.0.3 on 2018-06-07 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0027_stylist_service_time_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistservice',
            name='service_origin_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
