# Generated by Django 2.0.3 on 2018-06-07 10:42
from uuid import uuid4

from django.db import migrations


def populate_service_uuids(apps, schema_editor):
    StylistService = apps.get_model('salon', 'StylistService')
    for service in StylistService.all_objects.all():
        service_origin_uuid = service.service_uuid
        if not service_origin_uuid:
            service_origin_uuid = uuid4()
        service.service_origin_uuid = service_origin_uuid
        service.uuid = uuid4()
        service.save(update_fields=['uuid', 'service_origin_uuid', ])

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0028_auto_20180607_0642'),
    ]

    operations = [
        migrations.RunPython(populate_service_uuids, migrations.RunPython.noop),
    ]
