# Generated by Django 2.0.3 on 2018-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0036_auto_20180625_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
    ]
