# Generated by Django 2.0.3 on 2018-07-02 17:59

from django.db import migrations
import phonenumbers

def set_validated_phonenumber(apps, schema_editor):
    Invitation = apps.get_model('salon', 'Invitation')
    for invitation in Invitation.objects.all():
        phone_number_to_save = ''
        try:
            phonenumber_object = phonenumbers.parse(invitation.phone, "US")
            if phonenumbers.is_possible_number(phonenumber_object):
                phone_number_to_save = phonenumbers.format_number(
                    phonenumber_object, phonenumbers.PhoneNumberFormat.E164)
        except phonenumbers.NumberParseException:
            pass
        invitation.phone = phone_number_to_save
        invitation.save(update_fields=["phone"])

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0037_auto_20180628_1106'),
    ]

    operations = [
        migrations.RunPython(set_validated_phonenumber, migrations.RunPython.noop),
    ]
