# Generated by Django 2.0.3 on 2018-07-10 16:28

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    Stylist = apps.get_model('salon', 'Stylist')
    for stylist in Stylist.objects.all():
        stylist.uuid = uuid.uuid4()
        stylist.save()

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0039_auto_20180709_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
    ]
