# Generated by Django 2.0.3 on 2018-07-10 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0040_stylist_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
