# Generated by Django 2.0.3 on 2018-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0041_auto_20180710_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='is_maximum_discount_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stylist',
            name='maximum_discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
