# Generated by Django 2.0.3 on 2018-07-20 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0042_auto_20180717_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_3_weeks_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_4_weeks_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_5_weeks_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='stylist',
            name='rebook_within_6_weeks_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
