# Generated by Django 2.0.3 on 2018-07-24 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0043_auto_20180720_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
