# Generated by Django 2.0.3 on 2018-07-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0044_salon_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='longitude',
        ),
    ]
