# Generated by Django 2.0.3 on 2018-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0047_auto_20180730_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
