# Generated by Django 2.0.3 on 2018-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0049_auto_20180801_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetemplate',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stylistservice',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
