# Generated by Django 2.1 on 2018-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0051_salon_is_address_geocoded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
