# Generated by Django 2.1 on 2018-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0052_auto_20180906_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
