# Generated by Django 2.1 on 2018-10-10 11:55

from django.db import migrations


def populate_real_client_field(apps, schema_editor):
    Invitation = apps.get_model('salon', 'Invitation')
    Client = apps.get_model('client', 'Client')
    for invitation in Invitation.objects.filter(
            created_client__isnull=False, created_real_client__isnull=True).iterator():
        real_client: Client = invitation.created_client.client
        invitation.created_real_client = real_client
        invitation.save(update_fields=['created_real_client', ])


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0054_invitation_created_real_client'),
    ]

    operations = [
        migrations.RunPython(populate_real_client_field, migrations.RunPython.noop)
    ]
