# Generated by Django 2.1 on 2018-10-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0058_auto_20181011_1246'),
        ('core', '0032_auto_20181011_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='created_real_client',
        ),
    ]
