# Generated by Django 2.1 on 2018-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0059_remove_invitation_created_real_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
