# Generated by Django 2.1 on 2018-10-17 15:52
from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor

from django.db import migrations
from django.db.migrations.state import StateApps

from api.v1.auth.utils import get_country_code_from_phone


def set_country_from_phone(apps: StateApps, schema_editor: PostGISSchemaEditor):
    Stylist = apps.get_model('salon', 'Stylist')
    stylists = Stylist.objects.filter(salon__country=None)
    for stylist in stylists.iterator():
        if stylist.salon and stylist.user.phone:
            salon = stylist.salon
            salon.country = get_country_code_from_phone(stylist.user.phone)
            salon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0060_salon_country'),
    ]

    operations = [
        migrations.RunPython(code=set_country_from_phone, reverse_code=migrations.RunPython.noop)
    ]
