# Generated by Django 2.1 on 2018-10-31 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0062_salon_public_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='salon',
            name='public_phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
