# Generated by Django 2.1 on 2018-11-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0064_auto_20181030_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='has_business_hours_set',
            field=models.NullBooleanField(default=False),
        ),
    ]
