# Generated by Django 2.1 on 2018-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0066_set_default_has_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='has_business_hours_set',
            field=models.BooleanField(default=False),
        ),
    ]
