# Generated by Django 2.1 on 2018-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0067_auto_20181106_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='google_calendar_auth_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='google_calendar_refresh_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
