# Generated by Django 2.1 on 2018-11-13 18:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0067_auto_20181106_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
                'db_table': 'speciality',
            },
        ),
        migrations.AddField(
            model_name='stylist',
            name='specialities',
            field=models.ManyToManyField(to='salon.Speciality'),
        ),
    ]
