# Generated by Django 2.1 on 2018-11-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0069_set_initial_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='google_access_token',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='google_integration_added_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='google_refresh_token',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
