# Generated by Django 2.1 on 2018-11-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0070_auto_20181116_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
