# Generated by Django 2.1 on 2018-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0071_stylist_deactivated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistSpecialAvailableDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_available_dates', to='salon.Stylist')),
            ],
        ),
    ]
