# Generated by Django 2.1 on 2018-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0074_auto_20181129_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
