# Generated by Django 2.1 on 2018-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0075_stylist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
