# Generated by Django 2.1 on 2018-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0077_auto_20181210_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='weight',
            field=models.IntegerField(default=0, help_text='sorted in DESCENDING order'),
        ),
    ]
