# Generated by Django 2.1 on 2018-12-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0079_create_default_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
