# Generated by Django 2.1 on 2018-12-22 13:54

from django.db import migrations, models
import salon.types


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0080_stylist_instagram_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default=salon.types.InvitationStatus('invited'), max_length=15),
        ),
    ]
