# Generated by Django 2.1 on 2018-12-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0081_auto_20181222_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='followup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitation',
            name='followup_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
