# Generated by Django 2.1 on 2019-01-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_client_sms_notifications_enabled'),
        ('salon', '0082_auto_20181230_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited_by_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='salon.Stylist'),
        ),
    ]
