# Generated by Django 2.1 on 2019-01-21 13:04
from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor
from django.db import migrations
from django.db.migrations.state import StateApps

from core.constants import DEFAULT_CARD_FEE, DEFAULT_TAX_RATE


def change_default_tax_and_card_fee(apps: StateApps, schema_editor: PostGISSchemaEditor):
    Stylist = apps.get_model('salon', 'Stylist')
    stylists = Stylist.objects.all()
    for stylist in stylists:
        stylist.tax_rate = DEFAULT_TAX_RATE
        stylist.card_fee = DEFAULT_CARD_FEE
        stylist.save()

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0085_auto_20190121_0645'),
    ]

    operations = [
        migrations.RunPython(
            change_default_tax_and_card_fee, migrations.RunPython.noop
        )
    ]
