# Generated by Django 2.1 on 2019-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0087_stylist_must_set_deal_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='must_set_deal_of_week',
            field=models.BooleanField(default=True),
        ),
    ]
