# Generated by Django 2.1 on 2019-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0088_auto_20190121_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistweekdaydiscount',
            name='is_deal_of_week',
            field=models.BooleanField(default=False),
        ),
    ]
