# Generated by Django 2.1 on 2019-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0090_invitation_invite_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='card_fee',
            field=models.DecimalField(decimal_places=5, default=0.0275, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='tax_rate',
            field=models.DecimalField(decimal_places=5, default=0.045, max_digits=6),
        ),
    ]
