# Generated by Django 2.1 on 2019-01-28 14:45
from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor
from django.db import migrations
from django.db.migrations.state import StateApps


def add_new_categories(apps: StateApps, schema_editor: PostGISSchemaEditor):
    ServiceCategory = apps.get_model('salon', 'ServiceCategory')
    ServiceCategory.objects.get_or_create(name='Nails', category_code='nails')
    ServiceCategory.objects.get_or_create(name='Waxing', category_code='waxing')
    ServiceCategory.objects.get_or_create(name='Facials', category_code='facials')
    ServiceCategory.objects.get_or_create(name='Massages', category_code='massages')
    ServiceCategory.objects.get_or_create(name='Eyebrows and Lashes', category_code='eyebrows-and-lashes')
    ServiceCategory.objects.get_or_create(name='Makeup', category_code='makeup')


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0091_auto_20190123_1344'),
    ]

    operations = [
        migrations.RunPython(
            add_new_categories, migrations.RunPython.noop
        )
    ]
