# Generated by Django 2.1 on 2019-01-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0092_add_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
