# Generated by Django 2.1 on 2019-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0093_stylist_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='stripe_access_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stylist',
            name='stripe_refresh_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
