# Generated by Django 2.1 on 2019-02-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0094_auto_20190215_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
