# Generated by Django 2.1 on 2019-02-06 13:09

import billing.types
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0043_auto_20190129_1240'),
        ('client', '0032_client_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(billing.types.ChargeStatus('failed'), 'Failed'), (billing.types.ChargeStatus('pending'), 'Pending'), (billing.types.ChargeStatus('success'), 'Success')], default=billing.types.ChargeStatus('pending'), max_length=16)),
                ('stripe_id', models.CharField(max_length=64)),
                ('error_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.Appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('stripe_id', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[(billing.types.PaymentMethodType('card'), 'card')], default=billing.types.PaymentMethodType('card'), max_length=16)),
                ('card_brand', models.CharField(max_length=16)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('last_four_digits', models.CharField(max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.PaymentMethod'),
        ),
    ]
