# Generated by Django 2.1 on 2019-02-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190207_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='appointment.Appointment'),
        ),
    ]
