# Generated by Django 2.1 on 2019-02-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0094_auto_20190215_0853'),
        ('billing', '0003_auto_20190208_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stylist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.Stylist'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client'),
        ),
    ]
